# Generated by Django 4.0 on 2022-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEnquiry',
            fields=[
                ('VisitorId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Name', models.CharField(blank=True, max_length=225, null=True, verbose_name='Name')),
                ('Telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('Email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email Address')),
                ('SocialMediaLink', models.CharField(blank=True, max_length=155, null=True, verbose_name='Social Media Link')),
                ('HighestEducation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Highest Education')),
                ('Query', models.TextField(blank=True, null=True, verbose_name='Write Your Query')),
            ],
        ),
    ]
