# Generated by Django 4.0 on 2022-11-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorenquiry',
            options={'verbose_name': 'Visitor Enquiry', 'verbose_name_plural': 'Visitor Enquiries'},
        ),
        migrations.AlterModelTable(
            name='visitorenquiry',
            table='VisitorEnquiry',
        ),
    ]
